import React, { useState, useCallback, useMemo } from "react";
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  Alert,
  TextInput,
  ActivityIndicator,
} from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { useAccounts } from "../../hooks/useAccounts";
import { formatCurrency } from "../../utils/currency";

export const AccountsReceivableScreen = ({ navigation }) => {
  const {
    accountsReceivable,
    loading,
    error,
    refresh,
    searchReceivable,
    removeAccountReceivable,
    markReceivableAsPaid,
    receivableStats,
  } = useAccounts();

  const [searchQuery, setSearchQuery] = useState("");
  const [activeTab, setActiveTab] = useState("pending");

  const handleSearch = useCallback(
    async (query) => {
      setSearchQuery(query);
      if (!query.trim()) {
        await refresh();
      } else {
        await searchReceivable(query);
      }
    },
    [refresh, searchReceivable]
  );

  // Filtrar cuentas basado en el tab activo
  const filteredAccounts = useMemo(() => {
    if (activeTab === "pending") {
      return accountsReceivable.filter((account) => account.status !== "paid");
    } else if (activeTab === "paid") {
      return accountsReceivable.filter((account) => account.status === "paid");
    }
    return accountsReceivable;
  }, [accountsReceivable, activeTab]);

  const openAddScreen = useCallback(() => {
    navigation.navigate("AddAccountReceivable");
  }, [navigation]);

  const openEditScreen = useCallback(
    (account) => {
      navigation.navigate("EditAccountReceivable", { account });
    },
    [navigation]
  );

  const handleMarkAsPaid = useCallback(
    (account) => {
      Alert.alert(
        "Marcar como pagada",
        `¿Confirmar que la cuenta de ${
          account.customerName
        } por ${formatCurrency(account.amount || 0, "VES")} ha sido pagada?`,
        [
          { text: "Cancelar", style: "cancel" },
          {
            text: "Confirmar",
            onPress: async () => {
              try {
                await markReceivableAsPaid(account.id);
                Alert.alert("Éxito", "Cuenta marcada como pagada");
              } catch (err) {
                Alert.alert("Error", "No se pudo actualizar la cuenta");
              }
            },
          },
        ]
      );
    },
    [markReceivableAsPaid]
  );

  const handleDelete = useCallback(
    (account) => {
      Alert.alert(
        "Eliminar cuenta",
        `¿Eliminar la cuenta de ${account.customerName}?`,
        [
          { text: "Cancelar", style: "cancel" },
          {
            text: "Eliminar",
            style: "destructive",
            onPress: async () => {
              try {
                await removeAccountReceivable(account.id);
                Alert.alert("Éxito", "Cuenta eliminada correctamente");
              } catch (err) {
                Alert.alert("Error", "No se pudo eliminar la cuenta");
              }
            },
          },
        ]
      );
    },
    [removeAccountReceivable]
  );

  const totalAmount = receivableStats?.totalAmount || 0;
  const totalCount =
    typeof receivableStats?.total === "number"
      ? receivableStats.total
      : accountsReceivable.length;

  const getStatusAppearance = useCallback((status, dueDate) => {
    if (status === "paid") {
      return {
        label: "Pagada",
        backgroundColor: "#e5f7ed",
        color: "#2e7d32",
      };
    }

    if (dueDate && new Date(dueDate) < new Date()) {
      return {
        label: "Vencida",
        backgroundColor: "#fdecea",
        color: "#c62828",
      };
    }

    return {
      label: "Pendiente",
      backgroundColor: "#fff4e5",
      color: "#ef6c00",
    };
  }, []);

  const renderAccount = useCallback(
    ({ item }) => {
      const appearance = getStatusAppearance(item.status, item.dueDate);

      return (
        <TouchableOpacity
          style={styles.accountCard}
          activeOpacity={item.invoiceNumber ? 1 : 0.9}
          onPress={item.invoiceNumber ? undefined : () => openEditScreen(item)}
        >
          <View style={styles.cardHeader}>
            <Text style={styles.customerName}>{item.customerName}</Text>
            <View style={styles.statusContainer}>
              {item.invoiceNumber && (
                <View style={styles.autoGeneratedBadge}>
                  <Text style={styles.autoGeneratedText}>Auto</Text>
                </View>
              )}
              <View
                style={[
                  styles.statusBadge,
                  { backgroundColor: appearance.backgroundColor },
                ]}
              >
                <Text style={[styles.statusText, { color: appearance.color }]}>
                  {appearance.label}
                </Text>
              </View>
            </View>
          </View>

          <View style={styles.amountRow}>
            <Text style={styles.amount}>
              {formatCurrency(item.amount || 0, item.currency || "VES")}
            </Text>
            {item.dueDate ? (
              <Text style={styles.dueDate}>
                Vence {new Date(item.dueDate).toLocaleDateString()}
              </Text>
            ) : null}
          </View>

          {item.invoiceNumber ? (
            <Text style={styles.invoiceNumber}>
              Factura {item.invoiceNumber}
            </Text>
          ) : null}
          {item.documentNumber ? (
            <Text style={styles.metaText}>Cédula: {item.documentNumber}</Text>
          ) : null}
          {item.description ? (
            <Text style={styles.description}>{item.description}</Text>
          ) : null}
          {item.createdAt ? (
            <Text style={styles.metaText}>
              Registrada {new Date(item.createdAt).toLocaleDateString()}
            </Text>
          ) : null}

          <View style={styles.cardFooter}>
            {item.status !== "paid" ? (
              <TouchableOpacity
                style={styles.secondaryButton}
                onPress={() => handleMarkAsPaid(item)}
              >
                <Text style={styles.secondaryButtonText}>Registrar pago</Text>
              </TouchableOpacity>
            ) : null}

            <TouchableOpacity
              style={[
                styles.iconButton,
                item.status === "paid" && styles.iconButtonAlone,
              ]}
              onPress={() => handleDelete(item)}
            >
              <Text style={styles.iconButtonText}>🗑️</Text>
            </TouchableOpacity>
          </View>
        </TouchableOpacity>
      );
    },
    [getStatusAppearance, handleDelete, handleMarkAsPaid, openEditScreen]
  );

  const renderHeader = () => (
    <View>
      <View style={styles.summaryCard}>
        <View style={styles.summaryHeader}>
          <View style={styles.summaryIcon}>
            <Text style={styles.summaryIconText}>📥</Text>
          </View>
          <View>
            <Text style={styles.summaryTitle}>
              Cuentas por Cobrar ({totalCount})
            </Text>
          </View>
        </View>

        <Text style={styles.summaryAmount}>
          {formatCurrency(totalAmount, "VES")}
        </Text>
      </View>

      <View style={styles.controlsCard}>
        <View style={styles.searchWrapper}>
          <Text style={styles.searchIcon}>🔍</Text>
          <TextInput
            style={styles.searchInput}
            placeholder="Buscar cuentas..."
            placeholderTextColor="#9aa6b5"
            value={searchQuery}
            onChangeText={handleSearch}
            returnKeyType="search"
          />
        </View>
      </View>

      <View style={styles.tabGroup}>
        {[
          { key: "pending", label: "Pendientes" },
          { key: "paid", label: "Pagadas" },
        ].map((tab) => {
          const active = activeTab === tab.key;
          return (
            <TouchableOpacity
              key={tab.key}
              style={[styles.tabChip, active && styles.tabChipActive]}
              onPress={() => setActiveTab(tab.key)}
              activeOpacity={0.85}
            >
              <Text
                style={[styles.tabChipText, active && styles.tabChipTextActive]}
              >
                {tab.label}
              </Text>
            </TouchableOpacity>
          );
        })}
      </View>
    </View>
  );

  const renderEmpty = () => (
    <View style={styles.emptyState}>
      <View style={styles.emptyCard}>
        <Text style={styles.emptyIcon}>🗒️</Text>
        <Text style={styles.emptyTitle}>
          {searchQuery ? "Sin resultados" : "Aún no tienes cuentas"}
        </Text>
        <Text style={styles.emptySubtitle}>
          {searchQuery
            ? "Ajusta los términos de búsqueda para intentarlo de nuevo."
            : "Registra tu primera cuenta por cobrar desde el botón superior."}
        </Text>
      </View>
    </View>
  );

  useFocusEffect(
    useCallback(() => {
      refresh();
    }, [refresh])
  );

  if (loading) {
    return (
      <View style={styles.centerContainer}>
        <ActivityIndicator size="large" color="#4CAF50" />
        <Text style={styles.loadingText}>Cargando cuentas por cobrar...</Text>
      </View>
    );
  }

  if (error) {
    return (
      <View style={styles.centerContainer}>
        <Text style={styles.errorText}>
          Ocurrió un error al cargar la información.
        </Text>
        <TouchableOpacity style={styles.retryButton} onPress={refresh}>
          <Text style={styles.retryButtonText}>Reintentar</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <FlatList
        data={filteredAccounts}
        renderItem={renderAccount}
        keyExtractor={(item) => item.id.toString()}
        contentContainerStyle={styles.listContent}
        showsVerticalScrollIndicator={false}
        ListHeaderComponent={renderHeader}
        ListEmptyComponent={renderEmpty}
        refreshing={loading}
        onRefresh={refresh}
      />

      <TouchableOpacity
        style={styles.fab}
        onPress={openAddScreen}
        activeOpacity={0.85}
      >
        <Text style={styles.fabIcon}>+</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8edf2",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e8edf2",
    paddingHorizontal: 24,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: "#6c7a8a",
  },
  errorText: {
    fontSize: 15,
    color: "#c62828",
    textAlign: "center",
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
  retryButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 36,
  },
  summaryCard: {
    backgroundColor: "#fff",
    borderRadius: 22,
    padding: 18,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 6,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  summaryIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#ecf4ef",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  summaryIconText: {
    fontSize: 24,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2f3a4c",
  },
  summaryAmount: {
    fontSize: 30,
    fontWeight: "700",
    color: "#2f3a4c",
    marginBottom: 0,
  },
  controlsCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 4,
  },
  searchWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f4f7fb",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dde4ed",
    paddingHorizontal: 14,
    height: 48,
  },
  searchIcon: {
    fontSize: 18,
    color: "#6c7a8a",
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#2f3a4c",
  },
  primaryButton: {
    marginTop: 14,
    backgroundColor: "#4CAF50",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  accountCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  customerName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2f3a4c",
    flex: 1,
    marginRight: 12,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 18,
  },
  statusText: {
    fontSize: 13,
    fontWeight: "600",
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    marginBottom: 10,
  },
  amount: {
    fontSize: 22,
    fontWeight: "700",
    color: "#2e7d32",
  },
  dueDate: {
    fontSize: 13,
    color: "#6c7a8a",
    fontWeight: "500",
  },
  invoiceNumber: {
    fontSize: 13,
    color: "#4f6bed",
    fontWeight: "600",
    marginBottom: 6,
  },
  metaText: {
    fontSize: 13,
    color: "#6c7a8a",
    marginBottom: 4,
  },
  description: {
    fontSize: 13,
    color: "#4c5c6e",
    lineHeight: 19,
    marginBottom: 8,
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 14,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: "#edf8ef",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#2e7d32",
    fontWeight: "600",
    fontSize: 14,
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#fdecea",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },
  iconButtonAlone: {
    marginLeft: "auto",
  },
  iconButtonText: {
    fontSize: 20,
  },
  emptyState: {
    paddingTop: 40,
    alignItems: "center",
  },
  emptyCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  emptyIcon: {
    fontSize: 32,
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2f3a4c",
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#6c7a8a",
    textAlign: "center",
    lineHeight: 20,
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  autoGeneratedBadge: {
    backgroundColor: "#e8f4fd",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  autoGeneratedText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#2f5ae0",
    textTransform: "uppercase",
  },
  fab: {
    position: "absolute",
    bottom: 80,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#4CAF50",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  fabIcon: {
    fontSize: 28,
    color: "#fff",
    fontWeight: "bold",
  },
  tabGroup: {
    flexDirection: "row",
    backgroundColor: "#f3f5fa",
    borderRadius: 16,
    padding: 8,
    gap: 8,
  },
  tabChip: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  tabChipActive: {
    backgroundColor: "#2f5ae0",
    shadowColor: "#2f5ae0",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  tabChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#5b6472",
  },
  tabChipTextActive: {
    color: "#fff",
  },
});

export default AccountsReceivableScreen;
