// Monedas soportadas en la aplicación
export const CURRENCIES = {
  VES: {
    code: "VES",
    symbol: "VES.",
    name: "Bolívares",
    decimals: 2,
    position: "before", // before o after del monto
  },
  USD: {
    code: "USD",
    symbol: "USD",
    name: "Dólares",
    decimals: 2,
    position: "before",
  },
  COP: {
    code: "COP",
    symbol: "COP",
    name: "Pesos colombianos",
    decimals: 2,
    position: "before",
  },
  MXN: {
    code: "MXN",
    symbol: "MXN",
    name: "Pesos mexicanos",
    decimals: 2,
    position: "before",
  },
  PEN: {
    code: "PEN",
    symbol: "PEN",
    name: "Soles peruanos",
    decimals: 2,
    position: "before",
  },
  CLP: {
    code: "CLP",
    symbol: "CLP",
    name: "Pesos chilenos",
    decimals: 2,
    position: "before",
  },
  ARS: {
    code: "ARS",
    symbol: "ARS",
    name: "Pesos argentinos",
    decimals: 2,
    position: "before",
  },
  BOB: {
    code: "BOB",
    symbol: "BOB",
    name: "Bolivianos",
    decimals: 2,
    position: "before",
  },
  BRL: {
    code: "BRL",
    symbol: "BRL",
    name: "Reales brasileños",
    decimals: 2,
    position: "before",
  },
  PAB: {
    code: "PAB",
    symbol: "PAB",
    name: "Balboas panameños",
    decimals: 2,
    position: "before",
  },
  DOP: {
    code: "DOP",
    symbol: "DOP",
    name: "Pesos dominicanos",
    decimals: 2,
    position: "before",
  },
  UYU: {
    code: "UYU",
    symbol: "UYU",
    name: "Pesos uruguayos",
    decimals: 2,
    position: "before",
  },
  PYG: {
    code: "PYG",
    symbol: "PYG",
    name: "Guaraníes",
    decimals: 0,
    position: "before",
  },
  CRC: {
    code: "CRC",
    symbol: "CRC",
    name: "Colones costarricenses",
    decimals: 2,
    position: "before",
  },
  GTQ: {
    code: "GTQ",
    symbol: "GTQ",
    name: "Quetzales",
    decimals: 2,
    position: "before",
  },
  HNL: {
    code: "HNL",
    symbol: "HNL",
    name: "Lempiras",
    decimals: 2,
    position: "before",
  },
  NIO: {
    code: "NIO",
    symbol: "NIO",
    name: "Córdobas",
    decimals: 2,
    position: "before",
  },
  EUR: {
    code: "EUR",
    symbol: "EUR",
    name: "Euros",
    decimals: 2,
    position: "before",
  },
};

export const DEFAULT_CURRENCY = "VES";
export const SECONDARY_CURRENCY = "USD";
